vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%app.path.product_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
